### ISSUE TITLE
admin site doesn't hash password

### ISSUE THREAD

**Issue by agga1** [agga1/InzynieriaOprogramowania#20]
when creating user via dmin site, passwords are not hashed -
same problem as here:
https://stackoverflow.com/questions/32851901/django-admin-not-hashing-users-password
solution:
https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#custom-users-admin-full-example
-- create custom form for adding user

**Comment by macko99** [comment]
it should be ok now
when adding user from admin site:
- first we provide username and password
- next using 'save and continue editing' button we are redirect to page when we provide more user info like first name etc..

**Comment by macko99** [comment]
PR [https://github.com/agga1/InzynieriaOprogramowania/pull/21](https://github.com/agga1/InzynieriaOprogramowania/pull/21)

**Comment by agga1** [comment]
hashing works but now is_student is unavailable to set
